apis:
  pipefy: 
    config:
      host: https://api.pipefy.com/graphq
      authorization: access_token
      content_type: application/json
  
  zendesk:
    config:
      host: https://alpophelp.zendesk.com/api/v2/
      authorization: access_token
      content_type: application/json

  superlogica:
    config:
      host: https://api.superlogica.net/v2/
      authorization: access_token
      content_type: application/json
