catalog:
  pipefy: 
    config:
      host: https://api.pipefy.com/graphq
      authorization: access_token
      content_type: application/json
  
  zendesk:
    config:
      host: https://alpophelp.zendesk.com/api/v2/
      authorization: access_token
      content_type: application/json

  superlogica:
    config:
      host: https://apps.superlogica.net/imobiliaria/api/
      authorization: access_token
      content_type: application/json

  google_sheet:
    config:
      host: https://sheets.googleapis.com/v4/spreadsheets/
      authorization: access_token
      content_type: application/json
