credentials:
  pipefy:
    access_token: put_here_your_credentials
  
  zendesk:
    access_token: put_here_your_credentials

  superlogica:
    access_token: put_here_your_credentials
    app_token: put_here_your_credentials
  
  google_sheet:
    access_token: put_here_your_credentials
