queries:
  pipefy:
    card:
      find:
        query: '{"query":"{ card(id: \":id\") {title, pipe {id}}}"}'
      all:
        query: '{"query":"{ cards(pipe_id: \":pipe_id\", 
        first: 10){ edges { node {id title} } } }"}'
  zendesk:
    ticket:
      find:
        query: 'tickets/:id'
