queries:
  pipefy:
    card:
      find:
        query: '{"query":"{ card(id: \":id\") {title, pipe {id}}}"}'
      all:
        query: '{"query":"{ cards(pipe_id: \":pipe_id\", 
        first: 10){ edges { node {id title} } } }"}'
      create:
        query: '{"query" : "mutation{createCard(input:{pipe_id: :pipe_id,
        due_date: \":due_date\", assignee_ids: :assignee_ids, 
        phase_id: :phase_id, title: \":title\",
        fields_attributes: :fields_attributes}){card { id title } }}"}'
    phase:
      find:
        query: '{"query":"{ phase(id: \":id\") {phase {id}}}"}'
  zendesk:
    ticket:
      find:
        query: 'tickets/:id'
    user:
      find:
        query: 'user/:id'
  superlogica:
    cobranca:
      find:
        query: 'cobrancas?id=:id'
    contrato:
      find:
        query: 'contratos?id=:id&comDadosDosProprietarios=1&comDadosDosInquilinos=1'
